### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by pixelr0** [penk/qml-livereload#1]
Ubuntu 15.04 qt 5.3.2 i get segfault
[1]+  Segmentation fault      (core dumped) ./livereload

it kinda works for about 0.001 sec and then crashes, i can see a window created with the w/h specified in main.qml but that's it (i have the same code in main.qml as in example)

i have no idea how to future debug it :> welp

**Comment by penk** [comment]
Hi, I don't have 15.04 env at hand, but tested with Qt 5.2.1 on 14.10 without problem. Could you please provide more debug info, or try https://github.com/penk/terrarium-app instead?

**Comment by pixelr0** [comment]
gdb

``` bash
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea54f700 (LWP 25896)]
[New Thread 0x7fffdf8a7700 (LWP 25898)]

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106 ../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) bt full
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
No locals.
#1  0x00007ffff666c579 in QCoreApplication::arguments() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#2  0x00007fffed9cd34f in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
No symbol table info available.
#3  0x00007fffed9ce035 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
No symbol table info available.
#4  0x00007fffed161b28 in _SmcProcessMessage () from /usr/lib/x86_64-linux-gnu/libSM.so.6
No symbol table info available.
#5  0x00007fffecf53167 in IceProcessMessages () from /usr/lib/x86_64-linux-gnu/libICE.so.6
No symbol table info available.
#6  0x00007ffff6698b0d in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#7  0x00007ffff671861e in QSocketNotifier::activated(int, QSocketNotifier::QPrivateSignal) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#8  0x00007ffff66a629b in QSocketNotifier::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#9  0x00007ffff66697c5 in QCoreApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#10 0x00007ffff66698fb in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
```

**Comment by MidoriYakumo** [comment]
Maybe you are using ApplicationWindow Type?
It is conflict with QQuickView.
